### ISSUE TITLE
Sign in/Register does not work when active

### ISSUE THREAD

**Issue by Dennogin** [aaronldickman/nobloatfandom#1]
If signed out of your Fandom account and have the extension active, the sign in/register icons don't render properly and don't do anything when you click them. If this is intended it would be nice to have the option to allow sign in/register features enabled.

**Comment by aaronldickman** [comment]
Thanks for the report. Looks like removing the global navigation sidebar has some unintended side effects. Opted to just hide it with CSS instead. Should have a fix up shortly, google usually takes a few days after to approve new versions.

EDIT: Looks like this published. Make sure your extension is updated to 1.3.0

Looking at this after the fact I see that after logging in there's no way to log out since the nav bar is hidden. I'll see if I can't add a toggle for some of these elements.

**Comment by aaronldickman** [comment]
Config should have gone out yesterday. If you have 1.7.0 it should be available under the extension options.
